// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type DiaryNote struct {
	ID          int32
	UserID      int
	Text        string
	CreatedDate time.Time
	QuestionID  pgtype.Int4
}

type DiaryQuestion struct {
	ID        int32
	Text      string
	ShownDate pgtype.Date
}

type DiaryUser struct {
	ID         int32
	CreatedAt  time.Time
	Email      string
	Name       string
	Role       string
	SubID      pgtype.Text
	Subscribed bool
	Password   pgtype.Text
	TelegramID pgtype.Int8
}
