// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO diary.note (user_id, text, created_date, question_id) VALUES ($1, $2, $3, $4) RETURNING id, user_id, text, created_date, question_id
`

type CreateNoteParams struct {
	UserID      int
	Text        string
	CreatedDate time.Time
	QuestionID  pgtype.Int4
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (DiaryNote, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.UserID,
		arg.Text,
		arg.CreatedDate,
		arg.QuestionID,
	)
	var i DiaryNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.CreatedDate,
		&i.QuestionID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO diary.user (email, password, name) VALUES($1, $2, $3) RETURNING id, created_at, email, name, role, sub_id, subscribed, password, telegram_id
`

type CreateUserParams struct {
	Email    string
	Password pgtype.Text
	Name     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (DiaryUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Password, arg.Name)
	var i DiaryUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.SubID,
		&i.Subscribed,
		&i.Password,
		&i.TelegramID,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM diary.note WHERE id=$1
`

func (q *Queries) DeleteNote(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNoteById = `-- name: GetNoteById :one
SELECT id, user_id, text, created_date, question_id FROM diary.note WHERE id=$1
`

func (q *Queries) GetNoteById(ctx context.Context, id int32) (DiaryNote, error) {
	row := q.db.QueryRow(ctx, getNoteById, id)
	var i DiaryNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.CreatedDate,
		&i.QuestionID,
	)
	return i, err
}

const getNotes = `-- name: GetNotes :many
SELECT id, user_id, text, created_date, question_id FROM diary.note WHERE user_id=$1 AND question_id=$2 ORDER BY id ASC
`

type GetNotesParams struct {
	UserID     int
	QuestionID pgtype.Int4
}

func (q *Queries) GetNotes(ctx context.Context, arg GetNotesParams) ([]DiaryNote, error) {
	rows, err := q.db.Query(ctx, getNotes, arg.UserID, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryNote
	for rows.Next() {
		var i DiaryNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.CreatedDate,
			&i.QuestionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesByText = `-- name: GetNotesByText :many
SELECT id, user_id, text, created_date, question_id FROM diary.note WHERE user_id=$1 AND text ILIKE $2
`

type GetNotesByTextParams struct {
	UserID int
	Text   string
}

func (q *Queries) GetNotesByText(ctx context.Context, arg GetNotesByTextParams) ([]DiaryNote, error) {
	rows, err := q.db.Query(ctx, getNotesByText, arg.UserID, arg.Text)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryNote
	for rows.Next() {
		var i DiaryNote
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Text,
			&i.CreatedDate,
			&i.QuestionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, text, shown_date FROM diary.question WHERE id=$1
`

func (q *Queries) GetQuestion(ctx context.Context, id int32) (DiaryQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i DiaryQuestion
	err := row.Scan(&i.ID, &i.Text, &i.ShownDate)
	return i, err
}

const getQuestionByDate = `-- name: GetQuestionByDate :one
SELECT id, text, shown_date FROM diary.question WHERE shown_date=$1
`

func (q *Queries) GetQuestionByDate(ctx context.Context, shownDate pgtype.Date) (DiaryQuestion, error) {
	row := q.db.QueryRow(ctx, getQuestionByDate, shownDate)
	var i DiaryQuestion
	err := row.Scan(&i.ID, &i.Text, &i.ShownDate)
	return i, err
}

const getQuestions = `-- name: GetQuestions :many
SELECT id, text, shown_date FROM diary.question ORDER BY shown_date ASC
`

func (q *Queries) GetQuestions(ctx context.Context) ([]DiaryQuestion, error) {
	rows, err := q.db.Query(ctx, getQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryQuestion
	for rows.Next() {
		var i DiaryQuestion
		if err := rows.Scan(&i.ID, &i.Text, &i.ShownDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsLike = `-- name: GetQuestionsLike :many
SELECT id, text, shown_date FROM diary.question WHERE text ILIKE $1 ORDER BY shown_date ASC
`

func (q *Queries) GetQuestionsLike(ctx context.Context, text string) ([]DiaryQuestion, error) {
	rows, err := q.db.Query(ctx, getQuestionsLike, text)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DiaryQuestion
	for rows.Next() {
		var i DiaryQuestion
		if err := rows.Scan(&i.ID, &i.Text, &i.ShownDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, email, name, role, sub_id, subscribed, password, telegram_id FROM diary.user WHERE email=$1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (DiaryUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i DiaryUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.SubID,
		&i.Subscribed,
		&i.Password,
		&i.TelegramID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, created_at, email, name, role, sub_id, subscribed, password, telegram_id FROM diary.user WHERE id=$1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (DiaryUser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i DiaryUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.SubID,
		&i.Subscribed,
		&i.Password,
		&i.TelegramID,
	)
	return i, err
}

const getUserByTelegramId = `-- name: GetUserByTelegramId :one
SELECT id, created_at, email, name, role, sub_id, subscribed, password, telegram_id FROM diary.user WHERE telegram_id=$1
`

func (q *Queries) GetUserByTelegramId(ctx context.Context, telegramID pgtype.Int8) (DiaryUser, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramId, telegramID)
	var i DiaryUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.SubID,
		&i.Subscribed,
		&i.Password,
		&i.TelegramID,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE diary.note SET text=$1 WHERE id=$2 RETURNING id, user_id, text, created_date, question_id
`

type UpdateNoteParams struct {
	Text string
	ID   int32
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (DiaryNote, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.Text, arg.ID)
	var i DiaryNote
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Text,
		&i.CreatedDate,
		&i.QuestionID,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :one
UPDATE diary.question SET text=$1 WHERE id=$2 RETURNING id, text, shown_date
`

type UpdateQuestionParams struct {
	Text string
	ID   int32
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) (DiaryQuestion, error) {
	row := q.db.QueryRow(ctx, updateQuestion, arg.Text, arg.ID)
	var i DiaryQuestion
	err := row.Scan(&i.ID, &i.Text, &i.ShownDate)
	return i, err
}

const upsertTelegramUser = `-- name: UpsertTelegramUser :one
INSERT INTO diary.user (email, name, telegram_id)
VALUES ($1, $2, $3)
ON CONFLICT (telegram_id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, created_at, email, name, role, sub_id, subscribed, password, telegram_id
`

type UpsertTelegramUserParams struct {
	Email      string
	Name       string
	TelegramID pgtype.Int8
}

func (q *Queries) UpsertTelegramUser(ctx context.Context, arg UpsertTelegramUserParams) (DiaryUser, error) {
	row := q.db.QueryRow(ctx, upsertTelegramUser, arg.Email, arg.Name, arg.TelegramID)
	var i DiaryUser
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.SubID,
		&i.Subscribed,
		&i.Password,
		&i.TelegramID,
	)
	return i, err
}
